// <auto-generated />
namespace AgentDistribution.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class delivery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delivery));
        
        string IMigrationMetadata.Id
        {
            get { return "201612291433251_delivery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
